### ISSUE TITLE
Cannot launch while trying to use Nix to provide jdtls.

### ISSUE THREAD

**Issue by trev-dev** [yveszoundi/eglot-java#46]
I really enjoy this package, but it wholly expects us to let it manage the download and build of the JDT Language Server.

This is fine for most cases.  However, if you're a weirdo like me, who strives to make their configurations work as reliably as possible across systems, we like to use things like Nix/OS to provide runtime dependencies.  This is mainly because in the nixpkgs stable checkout we can usually expect all of the runtime dependencies to work together really well.  When we update our things, if they break due to some change in requirements, we can roll back until such a time that we can investigate what changed.

It would be nice if we could configure eglot-java to not have hard-coded paths to the jdt language server launcher, or the launcher config directory.  Or better yet, be able to take an arbitrary launch command for the [guess contact](https://github.com/yveszoundi/eglot-java/blob/main/eglot-java.el#L393) function to accept and use to bypass the built-in convenience features :)

Thoughts?

**Comment by yveszoundi** [comment]
Thanks for the kind words.

I understand for Nix/OS, I've used it many years ago for a while. I also do have a Gnu Guix installation around, but I don't program on that machine (similar concepts).
- For the JDT language server, you can manually manage the JDT server location, with the `eglot-java-server-install-dir` variable.
- The variable `eglot-java-eclipse-jdt-cache-directory` might also be of interest

I believe that the 2 above-mentioned variables should be enough for a NixOS `home-manager` configuration,
- As long as you're pointing `eglot-java` to the root folder of your jdtls installation, it should figure out automatically how to pick up the correct `config` folder (mac, unix, windows).
- If you've got a "non-standard"  `jdtls` folder structure, then I need to know what it looks like.

**Comment by trev-dev** [comment]
Amazing.  I'm pretty sure it's the config file that's tripping `eglot-java` up, as I'm fairly sure I set `eglot-java-server-install-dir` correctly.  The config is not in a downstream folder, and the nix just outputs the correct config.ini and produces only one.

Depending on which version of nixpkgs you use, you may have `jdt-language-server` as a binary, or `jdtls`.  If you're on 23.11 like I am, you use `JAVA_OPTS` to set your extra vmargs.  If you use unstable, it's jdtls and you pass it all through the command line flags.

But you can still just use the jar file in either case.  Does `eglot-java-eclipse-jdt-cache-directory` resolve the runtime issues with the plugin directory being immutable?

```
/nix/store/15dvj1sywr30z2j9ffdh07kgy75jr010-jdt-language-server-1.26.0 λ nix run nixpkgs#tree .
.
├── bin
│   └── jdt-language-server
└── share
    ├── config
    │   └── config.ini
    └── java
        └── plugins
            ├── ch.qos.logback.classic_1.2.12.jar
            ├── ch.qos.logback.core_1.2.12.jar
            ├── com.google.gson_2.10.1.v20230109-0753.jar
            ├── com.google.guava_30.1.0.v20221112-0806.jar
            ├── com.sun.jna_5.13.0.jar
            ├── com.sun.jna.platform_5.13.0.jar
            ├── javax.annotation_1.3.5.v20230504-0748.jar
            ├── javax.inject_1.0.0.v20220405-0441.jar
            ├── org.apache.ant_1.10.12.v20211102-1452.jar
            ├── org.apache.commons.cli_1.5.0.jar
            ├── org.apache.commons.codec_1.14.0.v20221112-0806.jar
            ├── org.apache.commons.lang3_3.1.0.v201403281430.jar
            ├── org.apache.felix.scr_2.2.6.jar
            ├── org.eclipse.ant.core_3.7.100.v20230726-0617.jar
            ├── org.eclipse.buildship.compat_3.1.7.v20221108-1729-s.jar
            ├── org.eclipse.buildship.core_3.1.7.v20221108-1729-s.jar
            ├── org.eclipse.compare.core_3.8.100.v20230726-0617.jar
            ├── org.eclipse.core.commands_3.11.100.v20230708-0916.jar
            ├── org.eclipse.core.contenttype_3.9.100.v20230630-1232.jar
            ├── org.eclipse.core.expressions_3.9.100.v20230726-0617.jar
            ├── org.eclipse.core.filebuffers_3.8.100.v20230701-0639.jar
            ├── org.eclipse.core.filesystem_1.10.100.v20230717-1727.jar
            ├── org.eclipse.core.jobs_3.15.0.v20230725-1354.jar
            ├── org.eclipse.core.net_1.5.100.v20230630-1232.jar
            ├── org.eclipse.core.net.linux_1.0.300.v20230630-1232.jar
            ├── org.eclipse.core.net.win32_1.1.100.v20230725-1354.jar
            ├── org.eclipse.core.net.win32.x86_64_1.2.100.v20230617-1158.jar
            ├── org.eclipse.core.resources_3.19.100.v20230726-0617.jar
            ├── org.eclipse.core.runtime_3.29.0.v20230726-0617.jar
            ├── org.eclipse.core.variables_3.6.100.v20230726-0617.jar
            ├── org.eclipse.debug.core_3.21.100.v20230726-0617.jar
            ├── org.eclipse.equinox.app_1.6.300.v20230630-1303.jar
            ├── org.eclipse.equinox.common_3.18.100.v20230630-1303.jar
            ├── org.eclipse.equinox.frameworkadmin_2.2.200.v20230630-1506.jar
            ├── org.eclipse.equinox.frameworkadmin.equinox_1.2.400.v20230630-1506.jar
            ├── org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar
            ├── org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.700.v20221108-1024.jar
            ├── org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024.jar
            ├── org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.700.v20221108-1024.jar
            ├── org.eclipse.equinox.preferences_3.10.300.v20230630-1303.jar
            ├── org.eclipse.equinox.registry_3.11.300.v20230630-1303.jar
            ├── org.eclipse.equinox.security_1.4.0.v20230630-1303.jar
            ├── org.eclipse.equinox.security.linux_1.1.0.v20230630-1303.jar
            ├── org.eclipse.equinox.security.macosx_1.102.0.v20230616-1215.jar
            ├── org.eclipse.equinox.security.win32.x86_64_1.2.0.v20230616-1215.jar
            ├── org.eclipse.equinox.simpleconfigurator_1.4.300.v20230630-1506.jar
            ├── org.eclipse.equinox.simpleconfigurator.manipulator_2.2.200.v20230630-1506.jar
            ├── org.eclipse.jdt.apt.core_3.8.100.v20230726-1449.jar
            ├── org.eclipse.jdt.apt.pluggable.core_1.4.100.v20230630-1307.jar
            ├── org.eclipse.jdt.core_3.35.0.v20230726-1449.jar
            ├── org.eclipse.jdt.core.compiler.batch_3.35.0.v20230721-1147.jar
            ├── org.eclipse.jdt.core.manipulation_1.19.100.v20230724-2209.jar
            ├── org.eclipse.jdt.debug_3.21.100.v20230714-0701.jar
            ├── org.eclipse.jdt.junit.core_3.12.100.v20230720-0542.jar
            ├── org.eclipse.jdt.junit.runtime_3.7.200.v20230627-0107.jar
            ├── org.eclipse.jdt.launching_3.20.100.v20230724-1759.jar
            ├── org.eclipse.jdt.launching.macosx_3.6.100.v20230630-1429.jar
            ├── org.eclipse.jdt.ls.core_1.26.0.202307271613.jar
            ├── org.eclipse.jdt.ls.filesystem_1.26.0.202307271613.jar
            ├── org.eclipse.jdt.ls.logback.appender_1.26.0.202307271613.jar
            ├── org.eclipse.lsp4j_0.21.0.v20230517-2120.jar
            ├── org.eclipse.lsp4j.jsonrpc_0.21.0.v20230517-2120.jar
            ├── org.eclipse.ltk.core.refactoring_3.14.100.v20230720-0542.jar
            ├── org.eclipse.m2e.apt.core_2.2.100.20230520-0934.jar
            ├── org.eclipse.m2e.core_2.0.8.20230520-0934.jar
            ├── org.eclipse.m2e.jdt_2.3.0.20230523-2033.jar
            ├── org.eclipse.m2e.maven.runtime_3.9.100.20230519-1558.jar
            ├── org.eclipse.m2e.workspace.cli_0.3.1.jar
            ├── org.eclipse.osgi_3.18.500.v20230709-1406.jar
            ├── org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
            ├── org.eclipse.osgi.services_3.11.100.v20221006-1531.jar
            ├── org.eclipse.text_3.13.100.v20230725-1107.jar
            ├── org.eclipse.xtext.xbase.lib_2.31.0.v20230529-0659.jar
            ├── org.gradle.toolingapi_7.4.2.v20220712-0930-s.jar
            ├── org.hamcrest.core_1.3.0.v20230721-0740.jar
            ├── org.junit_4.13.2.v20230725-0701.jar
            ├── org.osgi.service.cm_1.6.1.202109301733.jar
            ├── org.osgi.service.component_1.5.1.202212101352.jar
            ├── org.osgi.service.device_1.1.1.202109301733.jar
            ├── org.osgi.service.event_1.4.1.202109301733.jar
            ├── org.osgi.service.metatype_1.4.1.202109301733.jar
            ├── org.osgi.service.prefs_1.1.2.202109301733.jar
            ├── org.osgi.service.provisioning_1.2.0.201505202024.jar
            ├── org.osgi.service.upnp_1.2.1.202109301733.jar
            ├── org.osgi.service.useradmin_1.1.1.202109301733.jar
            ├── org.osgi.service.wireadmin_1.0.2.202109301733.jar
            ├── org.osgi.util.function_1.2.0.202109301733.jar
            ├── org.osgi.util.promise_1.3.0.202212101352.jar
            └── slf4j.api_1.7.36.jar
```

**Comment by trev-dev** [comment]
I'm confident that I had set `eglot-java-server-install-dir` correctly, but it's the configuration that's weird/non-standard.  It isn't in a downward directory, and when nix stores the build, it only provides the correct config for the system it was built for.

I really enjoy Guix too!  It's the software availability and the flakes feature that keep me maining on Nix though.  I'm on IRC/Matrix if you want to nerd out :)

Here's the file tree for the store files:

```
/nix/store/15dvj1sywr30z2j9ffdh07kgy75jr010-jdt-language-server-1.26.0 λ nix run nixpkgs#tree .
.
├── bin
│   └── jdt-language-server
└── share
    ├── config
    │   └── config.ini
    └── java
        └── plugins
            ├── ch.qos.logback.classic_1.2.12.jar
            ├── ch.qos.logback.core_1.2.12.jar
            ├── com.google.gson_2.10.1.v20230109-0753.jar
            ├── com.google.guava_30.1.0.v20221112-0806.jar
            ├── com.sun.jna_5.13.0.jar
            ├── com.sun.jna.platform_5.13.0.jar
            ├── javax.annotation_1.3.5.v20230504-0748.jar
            ├── javax.inject_1.0.0.v20220405-0441.jar
            ├── org.apache.ant_1.10.12.v20211102-1452.jar
            ├── org.apache.commons.cli_1.5.0.jar
            ├── org.apache.commons.codec_1.14.0.v20221112-0806.jar
            ├── org.apache.commons.lang3_3.1.0.v201403281430.jar
            ├── org.apache.felix.scr_2.2.6.jar
            ├── org.eclipse.ant.core_3.7.100.v20230726-0617.jar
            ├── org.eclipse.buildship.compat_3.1.7.v20221108-1729-s.jar
            ├── org.eclipse.buildship.core_3.1.7.v20221108-1729-s.jar
            ├── org.eclipse.compare.core_3.8.100.v20230726-0617.jar
            ├── org.eclipse.core.commands_3.11.100.v20230708-0916.jar
            ├── org.eclipse.core.contenttype_3.9.100.v20230630-1232.jar
            ├── org.eclipse.core.expressions_3.9.100.v20230726-0617.jar
            ├── org.eclipse.core.filebuffers_3.8.100.v20230701-0639.jar
            ├── org.eclipse.core.filesystem_1.10.100.v20230717-1727.jar
            ├── org.eclipse.core.jobs_3.15.0.v20230725-1354.jar
            ├── org.eclipse.core.net_1.5.100.v20230630-1232.jar
            ├── org.eclipse.core.net.linux_1.0.300.v20230630-1232.jar
            ├── org.eclipse.core.net.win32_1.1.100.v20230725-1354.jar
            ├── org.eclipse.core.net.win32.x86_64_1.2.100.v20230617-1158.jar
            ├── org.eclipse.core.resources_3.19.100.v20230726-0617.jar
            ├── org.eclipse.core.runtime_3.29.0.v20230726-0617.jar
            ├── org.eclipse.core.variables_3.6.100.v20230726-0617.jar
            ├── org.eclipse.debug.core_3.21.100.v20230726-0617.jar
            ├── org.eclipse.equinox.app_1.6.300.v20230630-1303.jar
            ├── org.eclipse.equinox.common_3.18.100.v20230630-1303.jar
            ├── org.eclipse.equinox.frameworkadmin_2.2.200.v20230630-1506.jar
            ├── org.eclipse.equinox.frameworkadmin.equinox_1.2.400.v20230630-1506.jar
            ├── org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar
            ├── org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.700.v20221108-1024.jar
            ├── org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.700.v20221108-1024.jar
            ├── org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.700.v20221108-1024.jar
            ├── org.eclipse.equinox.preferences_3.10.300.v20230630-1303.jar
            ├── org.eclipse.equinox.registry_3.11.300.v20230630-1303.jar
            ├── org.eclipse.equinox.security_1.4.0.v20230630-1303.jar
            ├── org.eclipse.equinox.security.linux_1.1.0.v20230630-1303.jar
            ├── org.eclipse.equinox.security.macosx_1.102.0.v20230616-1215.jar
            ├── org.eclipse.equinox.security.win32.x86_64_1.2.0.v20230616-1215.jar
            ├── org.eclipse.equinox.simpleconfigurator_1.4.300.v20230630-1506.jar
            ├── org.eclipse.equinox.simpleconfigurator.manipulator_2.2.200.v20230630-1506.jar
            ├── org.eclipse.jdt.apt.core_3.8.100.v20230726-1449.jar
            ├── org.eclipse.jdt.apt.pluggable.core_1.4.100.v20230630-1307.jar
            ├── org.eclipse.jdt.core_3.35.0.v20230726-1449.jar
            ├── org.eclipse.jdt.core.compiler.batch_3.35.0.v20230721-1147.jar
            ├── org.eclipse.jdt.core.manipulation_1.19.100.v20230724-2209.jar
            ├── org.eclipse.jdt.debug_3.21.100.v20230714-0701.jar
            ├── org.eclipse.jdt.junit.core_3.12.100.v20230720-0542.jar
            ├── org.eclipse.jdt.junit.runtime_3.7.200.v20230627-0107.jar
            ├── org.eclipse.jdt.launching_3.20.100.v20230724-1759.jar
            ├── org.eclipse.jdt.launching.macosx_3.6.100.v20230630-1429.jar
            ├── org.eclipse.jdt.ls.core_1.26.0.202307271613.jar
            ├── org.eclipse.jdt.ls.filesystem_1.26.0.202307271613.jar
            ├── org.eclipse.jdt.ls.logback.appender_1.26.0.202307271613.jar
            ├── org.eclipse.lsp4j_0.21.0.v20230517-2120.jar
            ├── org.eclipse.lsp4j.jsonrpc_0.21.0.v20230517-2120.jar
            ├── org.eclipse.ltk.core.refactoring_3.14.100.v20230720-0542.jar
            ├── org.eclipse.m2e.apt.core_2.2.100.20230520-0934.jar
            ├── org.eclipse.m2e.core_2.0.8.20230520-0934.jar
            ├── org.eclipse.m2e.jdt_2.3.0.20230523-2033.jar
            ├── org.eclipse.m2e.maven.runtime_3.9.100.20230519-1558.jar
            ├── org.eclipse.m2e.workspace.cli_0.3.1.jar
            ├── org.eclipse.osgi_3.18.500.v20230709-1406.jar
            ├── org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
            ├── org.eclipse.osgi.services_3.11.100.v20221006-1531.jar
            ├── org.eclipse.text_3.13.100.v20230725-1107.jar
            ├── org.eclipse.xtext.xbase.lib_2.31.0.v20230529-0659.jar
            ├── org.gradle.toolingapi_7.4.2.v20220712-0930-s.jar
            ├── org.hamcrest.core_1.3.0.v20230721-0740.jar
            ├── org.junit_4.13.2.v20230725-0701.jar
            ├── org.osgi.service.cm_1.6.1.202109301733.jar
            ├── org.osgi.service.component_1.5.1.202212101352.jar
            ├── org.osgi.service.device_1.1.1.202109301733.jar
            ├── org.osgi.service.event_1.4.1.202109301733.jar
            ├── org.osgi.service.metatype_1.4.1.202109301733.jar
            ├── org.osgi.service.prefs_1.1.2.202109301733.jar
            ├── org.osgi.service.provisioning_1.2.0.201505202024.jar
            ├── org.osgi.service.upnp_1.2.1.202109301733.jar
            ├── org.osgi.service.useradmin_1.1.1.202109301733.jar
            ├── org.osgi.service.wireadmin_1.0.2.202109301733.jar
            ├── org.osgi.util.function_1.2.0.202109301733.jar
            ├── org.osgi.util.promise_1.3.0.202212101352.jar
            └── slf4j.api_1.7.36.jar

6 directories, 91 files
```

**Comment by yveszoundi** [comment]
I simulated the folder structure that you provided and I think that there are 3 main changes required.
- Allow optionally a custom `config` folder as you mentioned earlier (`eglot-java-eclipse-jdt-config-directory`)
- In `eglot-java--eclipse-jdt-contact`, do not modify in-place `eglot-java-eclipse-jdt-args`
- In `eglot-java--find-equinox-launcher`, find the relevant jar with a recursive search from the JDT LS root folder

**Comment by yveszoundi** [comment]
Can you please confirm that the changes work for you, before I merge them into the main branch?
See https://github.com/yveszoundi/eglot-java/blob/d09a4204ece16a5be4ddea71476ef87e565733bd/eglot-java.el

**Comment by trev-dev** [comment]
I feel like I'm so close with your file, but I'm getting `void function eglot-path-to-uri`

```elisp
;; Java Specific
(defvar td-eglot-java-lombok-path (concat td-nix-deps-lombok
                                             "/share/java/lombok.jar")
  "The path to the lombok library.")

(defvar td-eglot-java-debug-path (file-expand-wildcards
                                  (file-name-concat td-nix-deps-java-debug
                                                    "share/vscode/extensions"
                                                    "vscjava.vscode-java-debug"
                                                    "server/*.jar"))
  "The path to where Microsoft Java Debug is installed.")

(defvar td-eglot-java-test-path (file-expand-wildcards
                                 (file-name-concat td-nix-deps-java-test
                                                   "share/vscode/extensions"
                                                   "vscjava.vscode-java-test"
                                                   "server/*.jar"))
  "The path to the where the  Microsoft Java Test plugin is installed.")

(defun td-eglot-java-custom-init-options (_server _eglot-java-eclipse-jdt)
    "Custom options that will be merged with any default settings."
    `(:bundles ,(vconcat td-eglot-java-debug-path
                         td-eglot-java-test-path)))
(setq eglot-java-user-init-opts-fn 'td-eglot-java-custom-init-options)

(defun td-eglot-java-setup ()
  (setq eglot-java-server-install-dir (file-name-concat td-nix-deps-jdtls
                                                        "share/java/plugins"))
  (setq eglot-java-eclipse-jdt-config-directory (file-name-concat
                                                 td-nix-deps-jdtls
                                                 "share/config"))

  (setq eglot-java-eclipse-jdt-args (list "-Dosgi.sharedConfiguration.area.readOnly=true"
                                          (concat "-javaagent:"
                                                  td-eglot-java-lombok-path)))
```

**Comment by trev-dev** [comment]
Okay so it *is* working, but I'm running into some configuration problem that the built nix "binary" at `/bin/jdt-language-server` somehow solves.  This is not an unfamiliar place for me, it's definitely enough for me to know that that your patch works:

```
[stderr]  java.nio.file.FileSystemException: /nix/store/f4bck5zlwi9lw98pwcaxfb87n0qwix6k-jdt-language-server-1.26.0/share/config/org.eclipse.equinox.launcher: Read-only file system
[stderr]  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
[stderr]  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[stderr]  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[stderr]  	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
[stderr]  	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
[stderr]  	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
[stderr]  	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
[stderr]  	at org.eclipse.equinox.launcher.Main.extractFromJAR(Main.java:2305)
[stderr]  	at org.eclipse.equinox.launcher.Main.getLibraryFromFragment(Main.java:522)
[stderr]  	at org.eclipse.equinox.launcher.Main.getLibraryPath(Main.java:495)
[stderr]  	at org.eclipse.equinox.launcher.Main.setupJNI(Main.java:448)
[stderr]  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:571)
[stderr]  	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
[stderr]  	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
[stderr]  
[jsonrpc] D[07:36:13.429] Connection state change: `exited abnormally with code 15
```

**Comment by yveszoundi** [comment]
I think that there are probably additional JVM parameters set by the `jdt-language-server` script that could be useful?

- See also https://stackoverflow.com/questions/30142802/is-it-possible-to-have-a-read-only-shared-equinox-environment
- See also https://github.com/JessicaJHee/eclipse.jdt.ls/blob/d47ab763fd432b69a8feaa8b3150426f31354f69/org.eclipse.jdt.ls.product/scripts/jdtls.py#L95

**Comment by trev-dev** [comment]
This is what `jdt-language-server` is made of.  Yep I think this is good enough :)  Thanks Yves!
```bash
#! /nix/store/r9h133c9m8f6jnlsqzwf89zg9w0w78s8-bash-5.2-p15/bin/bash -e
exec "/nix/store/y2zyba01xj3jdhlwlnv74fszpa9yqkib-openjdk-19.0.2+7/bin/java"  \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dosgi.sharedConfiguration.area=/nix/store/15dvj1sywr30z2j9ffdh07kgy75jr010-jdt-language-server-1.26.0/share/config \
  -Dosgi.sharedConfiguration.area.readOnly=true \
  -Dosgi.checkConfiguration=true \
  -Dosgi.configuration.cascaded=true \
  -Dlog.level=ALL $JAVA_OPTS \
  -jar /nix/store/15dvj1sywr30z2j9ffdh07kgy75jr010-jdt-language-server-1.26.0/share/java/plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED "$@"
```
