### ISSUE TITLE
eglot-java-user-init-opts-fn seems broken.

### ISSUE THREAD

**Issue by huangfeiyu** [yveszoundi/eglot-java#54]
Hi @yveszoundi I want to customize initialOptions, I following your guide to create the following configuration. It doesn't work. Eglot reports internal error. It works fine without the following customization.
```lisp
(setq eglot-java-user-init-opts-fn 'custom-eglot-java-init-opts)
(defun custom-eglot-java-init-opts (server eglot-java-eclipse-jdt)
  "Custom options that will be merged with any default settings."
  '(:settings
    (                                                                                                                                           
     :java                                                                                                                                      
     (                                                                                                                                          
      :configuration (:runtimes [(:name "JavaSE-11" :path "/usr/local/jdk-11.0.21+9" :sources "/usr/local/jdk-11.0.21+9/lib/src.zip" :default t)
                                 (:name "JavaSE-17" :path "/usr/lib/jvm/java-17-openjdk-amd64")])                                               
      :saveActions (:organizeImports t)                                                                                                         
      :completion (                                                                                                                             
                   :enabled t                                                                                                                   
                   :overwrite t                                                                                                                 
                   :guessMethodArguments t                                                                                                      
                   :importOrder ["java", "javax", "jakarta", "org", "co", "com", "io", "net", "software", "com.etix", "test"])                  
      )                                                                                                                                         
     )                                                                                                                                          
    :bundles ["/home/huang/jdtls/com.microsoft.java.debug.plugin-0.51.1.jar"]                                                                   
    ))
```
The following log are in eglot event buffer.
```
[jsonrpc] D[14:17:04.411] Running language server: /usr/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Xmx1G -Xmx3G --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -javaagent:/home/huang/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar -jar /home/huang/.emacs.d/share/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.6.900.v20240613-2009.jar -configuration /home/huang/.emacs.d/share/eclipse.jdt.ls/config_linux -data /home/huang/.emacs.d/eglot-java-eclipse-jdt-cache/6122a8de898f7c35b7a77de4fcbfe4a4
[jsonrpc] e[14:17:04.412] --> initialize[1] {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"processId":640884,"clientInfo":{"name":"Eglot","version":"1.17"},"rootPath":"/home/huang/eclipse-projects/etix/","rootUri":"file:///home/huang/eclipse-projects/etix","initializationOptions":{"extendedClientCapabilities":{"classFileContentsSupport":true},"workspaceFolders":["file:///home/huang/eclipse-projects/etix"],"settings":{"java":{"configuration":{"runtimes":[{"name":"JavaSE-11","path":"/usr/local/jdk-11.0.21+9","sources":"/usr/local/jdk-11.0.21+9/lib/src.zip","default":true},{"name":"JavaSE-17","path":"/usr/lib/jvm/java-17-openjdk-amd64"}]},"saveActions":{"organizeImports":true},"completion":{"enabled":true,"overwrite":true,"guessMethodArguments":true,"importOrder":["java",{",":"javax"},{",":"jakarta"},{",":"org"},{",":"co"},{",":"com"},{",":"io"},{",":"net"},{",":"software"},{",":"com.etix"},{",":"test"}]}}},"bundles":["/home/huang/jdtls/com.microsoft.java.debug.plugin-0.51.1.jar"]},"capabilities":{"workspace":{"applyEdit":true,"executeCommand":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":false},"configuration":true,"workspaceFolders":true},"textDocument":{"synchronization":{"dynamicRegistration":false,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":false,"completionItem":{"snippetSupport":true,"deprecatedSupport":true,"resolveSupport":{"properties":["documentation","details","additionalTextEdits"]},"tagSupport":{"valueSet":[1]}},"contextSupport":true},"hover":{"dynamicRegistration":false,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":false,"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true},"documentationFormat":["markdown","plaintext"],"activeParameterSupport":true}},"references":{"dynamicRegistration":false},"definition":{"dynamicRegistration":false,"linkSupport":true},"declaration":{"dynamicRegistration":false,"linkSupport":true},"implementation":{"dynamicRegistration":false,"linkSupport":true},"typeDefinition":{"dynamicRegistration":false,"linkSupport":true},"documentSymbol":{"dynamicRegistration":false,"hierarchicalDocumentSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"documentHighlight":{"dynamicRegistration":false},"codeAction":{"dynamicRegistration":false,"resolveSupport":{"properties":["edit","command"]},"dataSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"isPreferredSupport":true},"formatting":{"dynamicRegistration":false},"rangeFormatting":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false},"inlayHint":{"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":false,"codeDescriptionSupport":false,"tagSupport":{"valueSet":[1,2]}}},"window":{"showDocument":{"support":true},"workDoneProgress":true},"general":{"positionEncodings":["utf-32","utf-8","utf-16"]},"experimental":{}},"workspaceFolders":[{"uri":"file:///home/huang/eclipse-projects/etix","name":"~/eclipse-projects/etix/"}]}}
[stderr]  WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
[stderr]  Oct 10, 2024 2:17:04 PM org.apache.aries.spifly.BaseActivator log
[stderr]  INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
[stderr]  Oct 10, 2024 2:17:04 PM org.apache.aries.spifly.BaseActivator log
[stderr]  INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
[jsonrpc] e[14:17:06.509] <-- window/logMessage {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":2,"message":"Oct 10, 2024, 2:17:05 PM The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.\nnull"}}
[stderr]  Oct 10, 2024 2:17:06 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
[stderr]  SEVERE: Internal error: class com.google.gson.internal.LinkedTreeMap cannot be cast to class java.lang.CharSequence (com.google.gson.internal.LinkedTreeMap is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @fb4304f; java.lang.CharSequence is in module java.base of loader 'bootstrap')
[stderr]  java.lang.ClassCastException: class com.google.gson.internal.LinkedTreeMap cannot be cast to class java.lang.CharSequence (com.google.gson.internal.LinkedTreeMap is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @fb4304f; java.lang.CharSequence is in module java.base of loader 'bootstrap')
[stderr]  	at java.base/java.lang.String.join(String.java:3329)
[stderr]  	at org.eclipse.jdt.ls.core.internal.preferences.Preferences.setImportOrder(Preferences.java:1722)
[stderr]  	at org.eclipse.jdt.ls.core.internal.preferences.Preferences.createFrom(Preferences.java:1243)
[stderr]  	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:117)
[stderr]  	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:109)
[stderr]  	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:68)
[stderr]  	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:283)
[stderr]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[stderr]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[stderr]  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[stderr]  	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[stderr]  	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
[stderr]  	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
[stderr]  	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
[stderr]  	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
[stderr]  	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
[stderr]  	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
[stderr]  	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
[stderr]  	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
[stderr]  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[stderr]  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[stderr]  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[stderr]  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[stderr]  	at java.base/java.lang.Thread.run(Thread.java:840)
[stderr]  
[jsonrpc] e[14:17:06.560] <-- initialize[1] {"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Internal error.","data":"java.lang.ClassCastException: class com.google.gson.internal.LinkedTreeMap cannot be cast to class java.lang.CharSequence (com.google.gson.internal.LinkedTreeMap is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @fb4304f; java.lang.CharSequence is in module java.base of loader \u0027bootstrap\u0027)\n\tat java.base/java.lang.String.join(String.java:3329)\n\tat org.eclipse.jdt.ls.core.internal.preferences.Preferences.setImportOrder(Preferences.java:1722)\n\tat org.eclipse.jdt.ls.core.internal.preferences.Preferences.createFrom(Preferences.java:1243)\n\tat org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:117)\n\tat org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:109)\n\tat org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:68)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:283)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:569)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)\n\tat org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\n"}}
[jsonrpc] D[14:17:06.560] Connection state change: `killed
'

----------b---y---e---b---y---e----------
[stderr]  
[stderr]  
[stderr]  nil
[stderr]  nil
[stderr]  Process EGLOT (etix/(java-ts-mode java-mode)) stderr finished

```

Thank you!

**Comment by huangfeiyu** [comment]
Oh, I realized that the problem is 
```
:importOrder ["java", "javax", "jakarta", "org", "co", "com", "io", "net", "software", "com.etix", "test"])
```
It should be 
```
:importOrder ["java" "javax" "jakarta" "org" "co" "com" "io" "net" "software" "com.etix" "test"])                  
```
without comma.
